import {
  Controller,
  Post,
  Body,
  UseGuards,
  Request,
  Get,
  Query,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBearerAuth,
  ApiBody,
} from '@nestjs/swagger';
import { RegistrationTokensService } from './registration-tokens.service';
import { RegistrationRequestsService } from './registration-requests.service';
import { GenerateTokenDto } from './dto/generate-token.dto';
import { ValidateTokenDto } from './dto/validate-token.dto';
import { CreateRegistrationRequestDto } from './dto/create-registration-request.dto';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { RolesGuard } from '../auth/guards/roles.guard';
import { Roles } from '../auth/decorators/roles.decorator';
import { Role } from '../users/schemas/user.schema';

interface AuthenticatedRequest extends Request {
  user: {
    userId: string;
    email: string;
    role: Role;
  };
}

@ApiTags('Registration Tokens')
@Controller('api/registration-tokens')
export class RegistrationTokensController {
  constructor(
    private readonly registrationTokensService: RegistrationTokensService,
    private readonly registrationRequestsService: RegistrationRequestsService,
  ) {}

  @Post('generate')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(Role.SUPER_ADMIN, Role.ADMIN, Role.SCHOOL_OWNER)
  @ApiBearerAuth('access-token')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Generate a registration token',
    description:
      'Generate a registration token for inviting users. Super Admin can generate tokens for School Owners. School Admins can generate tokens for Teachers and Headteachers.',
  })
  @ApiBody({ type: GenerateTokenDto })
  @ApiResponse({
    status: 201,
    description: 'Token generated successfully',
    schema: {
      example: {
        token: 'abc123def456...',
        role: 'teacher',
        schoolId: '507f1f77bcf86cd799439011',
        expiresAt: '2024-12-31T23:59:59Z',
        status: 'pending',
      },
    },
  })
  @ApiResponse({ status: 403, description: 'Insufficient permissions' })
  @ApiResponse({ status: 400, description: 'Invalid request' })
  async generateToken(
    @Body() generateTokenDto: GenerateTokenDto,
    @Request() req: AuthenticatedRequest,
  ) {
    // Service will automatically get schoolId from user's school if needed
    const token = await this.registrationTokensService.generateToken(
      generateTokenDto,
      req.user.userId,
      undefined, // Let service determine schoolId from user's school
    );

    return {
      token: token.token,
      role: token.role,
      schoolId: token.schoolId,
      expiresAt: token.expiresAt,
      status: token.status,
      createdAt: token.createdAt,
    };
  }

  @Post('validate')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Validate a registration token',
    description:
      'Validate a registration token before registration. Returns token details if valid.',
  })
  @ApiBody({ type: ValidateTokenDto })
  @ApiResponse({
    status: 200,
    description: 'Token is valid',
    schema: {
      example: {
        valid: true,
        role: 'teacher',
        schoolId: '507f1f77bcf86cd799439011',
        expiresAt: '2024-12-31T23:59:59Z',
      },
    },
  })
  @ApiResponse({ status: 400, description: 'Token is invalid, expired, or already used' })
  async validateToken(@Body() validateTokenDto: ValidateTokenDto) {
    const token = await this.registrationTokensService.validateToken(
      validateTokenDto.token,
    );

    return {
      valid: true,
      role: token.role,
      schoolId: token.schoolId,
      expiresAt: token.expiresAt,
    };
  }

  @Get('my-tokens')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(Role.SUPER_ADMIN, Role.ADMIN, Role.SCHOOL_OWNER)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'Get all tokens generated by the current user',
    description: 'Retrieve all registration tokens generated by the authenticated user',
  })
  @ApiResponse({
    status: 200,
    description: 'Tokens retrieved successfully',
  })
  async getMyTokens(
    @Request() req: AuthenticatedRequest,
    @Query('role') role?: Role,
  ) {
    const tokens = await this.registrationTokensService.getTokensByCreator(
      req.user.userId,
      role,
    );
    return tokens;
  }

  @Get('my-tokens/stats')
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(Role.SUPER_ADMIN, Role.ADMIN, Role.SCHOOL_OWNER)
  @ApiBearerAuth('access-token')
  @ApiOperation({
    summary: 'Get token statistics for the current user',
    description: 'Get statistics about tokens generated by the authenticated user',
  })
  @ApiResponse({
    status: 200,
    description: 'Statistics retrieved successfully',
  })
  async getTokenStats(@Request() req: AuthenticatedRequest) {
    return this.registrationTokensService.getTokenStats(req.user.userId);
  }

  // ==================== Registration Requests ====================

  @Post('requests')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({
    summary: 'Create a registration request',
    description:
      'Submit a registration request. Users can request to register by providing their full name, email, and optional additional notes.',
  })
  @ApiBody({ type: CreateRegistrationRequestDto })
  @ApiResponse({
    status: 201,
    description: 'Registration request created successfully',
    schema: {
      example: {
        _id: '507f1f77bcf86cd799439011',
        fullName: 'John Doe',
        email: 'user@example.com',
        additionalNotes: 'I would like to register as a school owner',
        status: 'pending',
        createdAt: '2024-01-01T00:00:00Z',
      },
    },
  })
  @ApiResponse({ status: 409, description: 'A request with this email already exists' })
  async createRegistrationRequest(
    @Body() createDto: CreateRegistrationRequestDto,
  ) {
    return this.registrationRequestsService.create(createDto);
  }
}

