export enum EventType {
  // User Events
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  USER_RESTORED = 'USER_RESTORED',

  // Teacher Events
  TEACHER_CREATED = 'TEACHER_CREATED',
  TEACHER_UPDATED = 'TEACHER_UPDATED',
  TEACHER_DELETED = 'TEACHER_DELETED',
  TEACHER_RESTORED = 'TEACHER_RESTORED',
  TEACHER_ASSIGNED_CLASS = 'TEACHER_ASSIGNED_CLASS',
  TEACHER_UNASSIGNED_CLASS = 'TEACHER_UNASSIGNED_CLASS',
  TEACHER_ASSIGNED_SUBJECT = 'TEACHER_ASSIGNED_SUBJECT',
  TEACHER_REMOVED_SUBJECT = 'TEACHER_REMOVED_SUBJECT',

  // Student Events
  STUDENT_CREATED = 'STUDENT_CREATED',
  STUDENT_UPDATED = 'STUDENT_UPDATED',
  STUDENT_DELETED = 'STUDENT_DELETED',
  STUDENT_RESTORED = 'STUDENT_RESTORED',
  STUDENT_ENROLLED = 'STUDENT_ENROLLED',
  STUDENT_UNENROLLED = 'STUDENT_UNENROLLED',

  // Class Events
  CLASS_CREATED = 'CLASS_CREATED',
  CLASS_UPDATED = 'CLASS_UPDATED',
  CLASS_DELETED = 'CLASS_DELETED',
  CLASS_RESTORED = 'CLASS_RESTORED',
  CLASS_ASSIGNED_SUBJECT = 'CLASS_ASSIGNED_SUBJECT',
  CLASS_REMOVED_SUBJECT = 'CLASS_REMOVED_SUBJECT',
  CLASS_ASSIGNED_TEACHER = 'CLASS_ASSIGNED_TEACHER',

  // Subject Events
  SUBJECT_CREATED = 'SUBJECT_CREATED',
  SUBJECT_UPDATED = 'SUBJECT_UPDATED',
  SUBJECT_DELETED = 'SUBJECT_DELETED',
  SUBJECT_ASSIGNED_TO_CLASS = 'SUBJECT_ASSIGNED_TO_CLASS',
  SUBJECT_REMOVED_FROM_CLASS = 'SUBJECT_REMOVED_FROM_CLASS',

  // Assessment Events
  ASSESSMENT_CREATED = 'ASSESSMENT_CREATED',
  ASSESSMENT_UPDATED = 'ASSESSMENT_UPDATED',
  ASSESSMENT_DELETED = 'ASSESSMENT_DELETED',
  ASSESSMENT_SOFT_DELETED = 'ASSESSMENT_SOFT_DELETED',

  // Marks Events
  MARKS_CREATED = 'MARKS_CREATED',
  MARKS_UPDATED = 'MARKS_UPDATED',
  MARKS_SUBMITTED = 'MARKS_SUBMITTED',
  MARKS_APPROVED = 'MARKS_APPROVED',

  // School Events
  SCHOOL_CREATED = 'SCHOOL_CREATED',
  SCHOOL_UPDATED = 'SCHOOL_UPDATED',
  SCHOOL_DELETED = 'SCHOOL_DELETED',

  // Head Teacher Events
  HEAD_TEACHER_CREATED = 'HEAD_TEACHER_CREATED',
  HEAD_TEACHER_UPDATED = 'HEAD_TEACHER_UPDATED',
  HEAD_TEACHER_DELETED = 'HEAD_TEACHER_DELETED',

  // Staff Events
  STAFF_CREATED = 'STAFF_CREATED',
  STAFF_UPDATED = 'STAFF_UPDATED',
  STAFF_DELETED = 'STAFF_DELETED',
}
